# -*- coding: utf-8 -*-
"""FedEX_Logistics_Performance_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJTsSPgUFYNHxhk7KIEaYToj9qC2dn6b
"""

# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
fedex_df = pd.read_csv('/content/SCMS_Delivery_History_Dataset.csv')
print('The dataset has be loaded')

# Dataset First Look
fedex_df.head(10)

# Dataset Rows & Columns count
fedex_df.shape

# Dataset Info
fedex_df.info()

# Dataset Duplicate Value Count
fedex_df.duplicated().sum()

# Missing Values/Null Values Count
fedex_df.isnull().sum()

# Visualizing the missing values
missing = fedex_df.isnull().mean() * 100
missing = missing[missing > 0]

plt.figure(figsize=(12,5))
missing.sort_values().plot(kind='barh')
plt.title("Missing Value Percentage per Column")
plt.xlabel("Percentage (%)")
plt.show()

# Dataset Columns
fedex_df.columns

# Dataset Describe
fedex_df.describe(include='all')

# Check Unique Values for each variable.
fedex_df.nunique()

#1-Clean Column Names
fedex_df.columns = fedex_df.columns.str.replace(" ", "_").str.lower()

fedex_df.columns

#Convert Date Columns
date_cols = ["PQ First Sent to Client Date", "PO Sent to Vendor Date",
             "Scheduled Delivery Date", "Delivered to Client Date"]

for col in date_cols:
    if col in fedex_df.columns:
        fedex_df[col] = pd.to_datetime(fedex_df[col], errors='coerce')

pd.set_option('display.max_columns', None)

#Convert Numeric Columns
num_cols = ["line_item_quantity", "line_item_value",
            "pack_price", "unit_price", "weight_kilograms", "freight_cost_usd"]

for col in num_cols:
    if col in fedex_df.columns:
        fedex_df[col] = pd.to_numeric(fedex_df[col], errors="coerce")

#Lead Time(in Days)
# Ensure date columns are converted to datetime type before calculation
fedex_df["delivered_to_client_date"] = pd.to_datetime(fedex_df["delivered_to_client_date"], errors='coerce')
fedex_df["po_sent_to_vendor_date"] = pd.to_datetime(fedex_df["po_sent_to_vendor_date"], errors='coerce')
fedex_df["lead_time"] = (fedex_df["delivered_to_client_date"] - fedex_df["po_sent_to_vendor_date"]).dt.days

#On-Time Delivery Flag
fedex_df["on_time"] = np.where(
    fedex_df["delivered_to_client_date"] <= fedex_df["scheduled_delivery_date"], 1, 0
)

print(fedex_df.columns.tolist())

#Basic KPIs
print("Total Shipments:", len(fedex_df))
print("Average Lead Time:", fedex_df["lead_time"].mean())
print("On-Time Delivery Rate:", fedex_df["on_time"].mean())

#Converting 'Weight_(kilogram)' and 'freight_cost_(usd)' datatype from 'Object' to 'float'
# Clean Weight (Kilograms)
fedex_df['weight_(kilograms)'] = (
    fedex_df['weight_(kilograms)']
    .astype(str)
    .str.replace(",", "")                # remove commas
    .str.replace("$", "")                # remove currency symbols (just in case)
    .str.extract(r'(\d*\.?\d+)')          # extract numeric part only
)

fedex_df['weight_(kilograms)'] = pd.to_numeric(fedex_df['weight_(kilograms)'], errors='coerce')

# Clean Freight Cost (USD)
fedex_df['freight_cost_(usd)'] = (
    fedex_df['freight_cost_(usd)']
    .astype(str)
    .str.replace(",", "")
    .str.replace("$", "")
    .str.extract(r'(\d*\.?\d+)')          # extract only digits + decimals
)

fedex_df['freight_cost_(usd)'] = pd.to_numeric(fedex_df['freight_cost_(usd)'], errors='coerce')


#Verify Conversion
fedex_df[['weight_(kilograms)', 'freight_cost_(usd)']].info()
fedex_df[['weight_(kilograms)', 'freight_cost_(usd)']].head()

#Handling Missing or Invalid Values
fedex_df['weight_(kilograms)'] = fedex_df['weight_(kilograms)'].fillna(fedex_df['weight_(kilograms)'].median())
fedex_df['freight_cost_(usd)'] = fedex_df['freight_cost_(usd)'].fillna(fedex_df['freight_cost_(usd)'].median())

#Freight Cost Per KG
# Replace 0 in weight_(kilograms) with NaN to avoid division by zero, then calculate freight_per_kg
fedex_df["freight_per_kg"] = fedex_df["freight_cost_(usd)"] / fedex_df["weight_(kilograms)"].replace(0, np.nan)

#Basic KPIs
print("Total Freight Cost:", fedex_df["freight_cost_(usd)"].sum())
print("Average Freight per KG:", fedex_df["freight_per_kg"].mean())



"""## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1 Lead Time Distribution
"""

plt.figure(figsize=(12,5))
sns.histplot(fedex_df["lead_time"].dropna(), bins=40, kde=True)
plt.title("Lead Time Distribution")
plt.xlabel("Days")
plt.ylabel("Count")
plt.show()

"""#### Chart - 2 Freight Cost Distribution"""

sns.histplot(fedex_df["freight_cost_(usd)"].dropna(), bins=40, kde=True)

"""#### Chart - 3 Freight Cost by Country (Top 5)

---


"""

if "country" in fedex_df.columns:
    top5 = fedex_df.groupby("country")["freight_cost_(usd)"].sum().sort_values(ascending=False).head(10)

    top5.plot(kind="bar")
    plt.title("Top 5 Countries by Freight Cost")
    plt.ylabel("Freight Cost (USD)")
    plt.show()

"""#### Chart - 4 Lead Time By Shippment Mode




"""

if "shipment_mode" in fedex_df.columns:
    sns.boxplot(x="shipment_mode", y="lead_time", data=fedex_df)
    plt.title("Lead Time by Shipment Mode")
    plt.xticks(rotation=45)
    plt.show()

"""#### Chart - 5 Monthly On-Time Delivery Trend"""

fedex_df["month"] = fedex_df["delivered_to_client_date"].dt.to_period("M")

monthly_ontime = fedex_df.groupby("month")["on_time"].mean()

monthly_ontime.plot(kind="line", marker="o")
plt.title("Monthly On-Time Delivery Trend")
plt.ylabel("On-Time Rate")
plt.show()

"""#### Chart - 6 Correlation Heatmap"""

num_df = fedex_df[["lead_time","line_item_value","freight_cost_(usd)","weight_(kilograms)","freight_per_kg"]]

plt.figure(figsize=(8,5))
sns.heatmap(num_df.corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.show()